### ISSUE TITLE
golang struct to send or receive vcard content

### ISSUE THREAD

**Issue by MarkCasiano** [mapaiva/vcard-go#3]
What was I thinking?...

Physical web. It would be easy to exchange contacts if physical web can be used to broadcast your vcard using golang and for someone to see and be able to save it on their smartphones. If this could be done, I'd like to incorporate in my personal site.

**Comment by mapaiva** [comment]
Hi @MarkCasiano, sorry for the late response.

I think it's indeed a good idea, however, kinda out of the scope of the project. `vcard-go` aims to be a golang library to decode `vcf` files, not a vCard exchanging service. But if you someday create something similar to this idea, please open a new issue here to expose your work. It'd be very welcome for sure.
